backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  # ---- 1) Info Cards (nested subtypes) ----
  - name: "infos"
    label: "Infos"
    folder: "src/pages/infos"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    nested:
      depth: 5         # allows /infos/<subtype>/<name>.md
      summary: "{{title}}"
    fields:
      - { label: "Name",  name: "name",  widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  # ---- 2) Social ----
  - name: "social"
    label: "Social"
    label_singular: "Social Link"
    folder: "src/pages/social"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Platform", name: "platform", widget: "string" }   # e.g., GitHub
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Username / Handle", name: "username", widget: "string", required: false }
      - { label: "Icon (emoji or short text)", name: "icon", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  # ---- 3) Skills ----
  - name: "skills"
    label: "Skills"
    label_singular: "Skill"
    folder: "src/pages/skills"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - label: "Level"
        name: "level"
        widget: "select"
        options: ["Beginner", "Intermediate", "Advanced", "A lot"]

  # ---- 4) Hobbies ----
  - name: "hobbies"
    label: "Hobbies"
    label_singular: "Hobby"
    folder: "src/pages/hobbies"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }   # can include emoji
      - { label: "Description", name: "description", widget: "text", required: false }
